// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	reportv1 "github.com/jinmukeji/platform-proto/gen/go/platform/report/v1"
)

// ReportAPIClient is an autogenerated mock type for the ReportAPIClient type
type ReportAPIClient struct {
	mock.Mock
}

// CountAdditionalReports provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIClient) CountAdditionalReports(ctx context.Context, in *reportv1.CountAdditionalReportsRequest, opts ...grpc.CallOption) (*reportv1.CountAdditionalReportsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.CountAdditionalReportsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.CountAdditionalReportsRequest, ...grpc.CallOption) *reportv1.CountAdditionalReportsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.CountAdditionalReportsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.CountAdditionalReportsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeveloperMeasurementInfo provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIClient) GetDeveloperMeasurementInfo(ctx context.Context, in *reportv1.GetDeveloperMeasurementInfoRequest, opts ...grpc.CallOption) (*reportv1.GetDeveloperMeasurementInfoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetDeveloperMeasurementInfoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetDeveloperMeasurementInfoRequest, ...grpc.CallOption) *reportv1.GetDeveloperMeasurementInfoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetDeveloperMeasurementInfoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetDeveloperMeasurementInfoRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonthlyReport provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIClient) GetMonthlyReport(ctx context.Context, in *reportv1.GetMonthlyReportRequest, opts ...grpc.CallOption) (*reportv1.GetMonthlyReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetMonthlyReportResponse
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetMonthlyReportRequest, ...grpc.CallOption) *reportv1.GetMonthlyReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetMonthlyReportResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetMonthlyReportRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRawData provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIClient) GetRawData(ctx context.Context, in *reportv1.GetRawDataRequest, opts ...grpc.CallOption) (*reportv1.GetRawDataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetRawDataResponse
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetRawDataRequest, ...grpc.CallOption) *reportv1.GetRawDataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetRawDataResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetRawDataRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReport provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIClient) GetReport(ctx context.Context, in *reportv1.GetReportRequest, opts ...grpc.CallOption) (*reportv1.GetReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetReportResponse
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetReportRequest, ...grpc.CallOption) *reportv1.GetReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetReportResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetReportRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWeeklyReport provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIClient) GetWeeklyReport(ctx context.Context, in *reportv1.GetWeeklyReportRequest, opts ...grpc.CallOption) (*reportv1.GetWeeklyReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetWeeklyReportResponse
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetWeeklyReportRequest, ...grpc.CallOption) *reportv1.GetWeeklyReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetWeeklyReportResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetWeeklyReportRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchReports provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIClient) SearchReports(ctx context.Context, in *reportv1.SearchReportsRequest, opts ...grpc.CallOption) (*reportv1.SearchReportsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.SearchReportsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchReportsRequest, ...grpc.CallOption) *reportv1.SearchReportsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.SearchReportsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.SearchReportsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitPulseTest provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIClient) SubmitPulseTest(ctx context.Context, in *reportv1.SubmitPulseTestRequest, opts ...grpc.CallOption) (*reportv1.SubmitPulseTestResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.SubmitPulseTestResponse
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SubmitPulseTestRequest, ...grpc.CallOption) *reportv1.SubmitPulseTestResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.SubmitPulseTestResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.SubmitPulseTestRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAnalysisPreset provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIClient) UpdateAnalysisPreset(ctx context.Context, in *reportv1.UpdateAnalysisPresetRequest, opts ...grpc.CallOption) (*reportv1.UpdateAnalysisPresetResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.UpdateAnalysisPresetResponse
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.UpdateAnalysisPresetRequest, ...grpc.CallOption) *reportv1.UpdateAnalysisPresetResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.UpdateAnalysisPresetResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.UpdateAnalysisPresetRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewReportAPIClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewReportAPIClient creates a new instance of ReportAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReportAPIClient(t mockConstructorTestingTNewReportAPIClient) *ReportAPIClient {
	mock := &ReportAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
