// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "go-micro.dev/v4/client"

	mock "github.com/stretchr/testify/mock"

	reportv1 "github.com/jinmukeji/huimaibao-proto/gen/go/huimaibao/biz/report/v1"
)

// ReportAPIService is an autogenerated mock type for the ReportAPIService type
type ReportAPIService struct {
	mock.Mock
}

// AddCustomerReport provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) AddCustomerReport(ctx context.Context, in *reportv1.AddCustomerReportRequest, opts ...client.CallOption) (*reportv1.AddCustomerReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.AddCustomerReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.AddCustomerReportRequest, ...client.CallOption) (*reportv1.AddCustomerReportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.AddCustomerReportRequest, ...client.CallOption) *reportv1.AddCustomerReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.AddCustomerReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.AddCustomerReportRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerConstitution provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetCustomerConstitution(ctx context.Context, in *reportv1.GetCustomerConstitutionRequest, opts ...client.CallOption) (*reportv1.GetCustomerConstitutionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetCustomerConstitutionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetCustomerConstitutionRequest, ...client.CallOption) (*reportv1.GetCustomerConstitutionResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetCustomerConstitutionRequest, ...client.CallOption) *reportv1.GetCustomerConstitutionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetCustomerConstitutionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetCustomerConstitutionRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerTrendency provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetCustomerTrendency(ctx context.Context, in *reportv1.GetCustomerTrendencyRequest, opts ...client.CallOption) (*reportv1.GetCustomerTrendencyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetCustomerTrendencyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetCustomerTrendencyRequest, ...client.CallOption) (*reportv1.GetCustomerTrendencyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetCustomerTrendencyRequest, ...client.CallOption) *reportv1.GetCustomerTrendencyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetCustomerTrendencyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetCustomerTrendencyRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationMonthlyReportCount provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetOrganizationMonthlyReportCount(ctx context.Context, in *reportv1.GetOrganizationMonthlyReportCountRequest, opts ...client.CallOption) (*reportv1.GetOrganizationMonthlyReportCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetOrganizationMonthlyReportCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetOrganizationMonthlyReportCountRequest, ...client.CallOption) (*reportv1.GetOrganizationMonthlyReportCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetOrganizationMonthlyReportCountRequest, ...client.CallOption) *reportv1.GetOrganizationMonthlyReportCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetOrganizationMonthlyReportCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetOrganizationMonthlyReportCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationReportCount provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetOrganizationReportCount(ctx context.Context, in *reportv1.GetOrganizationReportCountRequest, opts ...client.CallOption) (*reportv1.GetOrganizationReportCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetOrganizationReportCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetOrganizationReportCountRequest, ...client.CallOption) (*reportv1.GetOrganizationReportCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetOrganizationReportCountRequest, ...client.CallOption) *reportv1.GetOrganizationReportCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetOrganizationReportCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetOrganizationReportCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicSharedReport provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetPublicSharedReport(ctx context.Context, in *reportv1.GetPublicSharedReportRequest, opts ...client.CallOption) (*reportv1.GetPublicSharedReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetPublicSharedReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetPublicSharedReportRequest, ...client.CallOption) (*reportv1.GetPublicSharedReportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetPublicSharedReportRequest, ...client.CallOption) *reportv1.GetPublicSharedReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetPublicSharedReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetPublicSharedReportRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReport provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetReport(ctx context.Context, in *reportv1.GetReportRequest, opts ...client.CallOption) (*reportv1.GetReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetReportRequest, ...client.CallOption) (*reportv1.GetReportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetReportRequest, ...client.CallOption) *reportv1.GetReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetReportRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSharedReportLink provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetSharedReportLink(ctx context.Context, in *reportv1.GetSharedReportLinkRequest, opts ...client.CallOption) (*reportv1.GetSharedReportLinkResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetSharedReportLinkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetSharedReportLinkRequest, ...client.CallOption) (*reportv1.GetSharedReportLinkResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetSharedReportLinkRequest, ...client.CallOption) *reportv1.GetSharedReportLinkResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetSharedReportLinkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetSharedReportLinkRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTenantMonthlyReportCount provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetTenantMonthlyReportCount(ctx context.Context, in *reportv1.GetTenantMonthlyReportCountRequest, opts ...client.CallOption) (*reportv1.GetTenantMonthlyReportCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetTenantMonthlyReportCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetTenantMonthlyReportCountRequest, ...client.CallOption) (*reportv1.GetTenantMonthlyReportCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetTenantMonthlyReportCountRequest, ...client.CallOption) *reportv1.GetTenantMonthlyReportCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetTenantMonthlyReportCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetTenantMonthlyReportCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTenantReportCount provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetTenantReportCount(ctx context.Context, in *reportv1.GetTenantReportCountRequest, opts ...client.CallOption) (*reportv1.GetTenantReportCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetTenantReportCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetTenantReportCountRequest, ...client.CallOption) (*reportv1.GetTenantReportCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetTenantReportCountRequest, ...client.CallOption) *reportv1.GetTenantReportCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetTenantReportCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetTenantReportCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWeeklyReport provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) GetWeeklyReport(ctx context.Context, in *reportv1.GetWeeklyReportRequest, opts ...client.CallOption) (*reportv1.GetWeeklyReportResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.GetWeeklyReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetWeeklyReportRequest, ...client.CallOption) (*reportv1.GetWeeklyReportResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.GetWeeklyReportRequest, ...client.CallOption) *reportv1.GetWeeklyReportResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.GetWeeklyReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.GetWeeklyReportRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCustomerReports provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) ListCustomerReports(ctx context.Context, in *reportv1.ListCustomerReportsRequest, opts ...client.CallOption) (*reportv1.ListCustomerReportsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.ListCustomerReportsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListCustomerReportsRequest, ...client.CallOption) (*reportv1.ListCustomerReportsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListCustomerReportsRequest, ...client.CallOption) *reportv1.ListCustomerReportsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.ListCustomerReportsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.ListCustomerReportsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrganizationTenantMonthlyReportCount provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) ListOrganizationTenantMonthlyReportCount(ctx context.Context, in *reportv1.ListOrganizationTenantMonthlyReportCountRequest, opts ...client.CallOption) (*reportv1.ListOrganizationTenantMonthlyReportCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.ListOrganizationTenantMonthlyReportCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListOrganizationTenantMonthlyReportCountRequest, ...client.CallOption) (*reportv1.ListOrganizationTenantMonthlyReportCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListOrganizationTenantMonthlyReportCountRequest, ...client.CallOption) *reportv1.ListOrganizationTenantMonthlyReportCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.ListOrganizationTenantMonthlyReportCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.ListOrganizationTenantMonthlyReportCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListReports provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) ListReports(ctx context.Context, in *reportv1.ListReportsRequest, opts ...client.CallOption) (*reportv1.ListReportsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.ListReportsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListReportsRequest, ...client.CallOption) (*reportv1.ListReportsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListReportsRequest, ...client.CallOption) *reportv1.ListReportsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.ListReportsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.ListReportsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTempCustomerReports provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) ListTempCustomerReports(ctx context.Context, in *reportv1.ListTempCustomerReportsRequest, opts ...client.CallOption) (*reportv1.ListTempCustomerReportsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.ListTempCustomerReportsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListTempCustomerReportsRequest, ...client.CallOption) (*reportv1.ListTempCustomerReportsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListTempCustomerReportsRequest, ...client.CallOption) *reportv1.ListTempCustomerReportsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.ListTempCustomerReportsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.ListTempCustomerReportsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTopOrganizationReportCount provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) ListTopOrganizationReportCount(ctx context.Context, in *reportv1.ListTopOrganizationReportCountRequest, opts ...client.CallOption) (*reportv1.ListTopOrganizationReportCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.ListTopOrganizationReportCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListTopOrganizationReportCountRequest, ...client.CallOption) (*reportv1.ListTopOrganizationReportCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ListTopOrganizationReportCountRequest, ...client.CallOption) *reportv1.ListTopOrganizationReportCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.ListTopOrganizationReportCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.ListTopOrganizationReportCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModifyReportRemark provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) ModifyReportRemark(ctx context.Context, in *reportv1.ModifyReportRemarkRequest, opts ...client.CallOption) (*reportv1.ModifyReportRemarkResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.ModifyReportRemarkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ModifyReportRemarkRequest, ...client.CallOption) (*reportv1.ModifyReportRemarkResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ModifyReportRemarkRequest, ...client.CallOption) *reportv1.ModifyReportRemarkResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.ModifyReportRemarkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.ModifyReportRemarkRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModifyReportStaffRemark provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) ModifyReportStaffRemark(ctx context.Context, in *reportv1.ModifyReportStaffRemarkRequest, opts ...client.CallOption) (*reportv1.ModifyReportStaffRemarkResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.ModifyReportStaffRemarkResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ModifyReportStaffRemarkRequest, ...client.CallOption) (*reportv1.ModifyReportStaffRemarkResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.ModifyReportStaffRemarkRequest, ...client.CallOption) *reportv1.ModifyReportStaffRemarkResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.ModifyReportStaffRemarkResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.ModifyReportStaffRemarkRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchOrganizationReports provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) SearchOrganizationReports(ctx context.Context, in *reportv1.SearchOrganizationReportsRequest, opts ...client.CallOption) (*reportv1.SearchOrganizationReportsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.SearchOrganizationReportsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchOrganizationReportsRequest, ...client.CallOption) (*reportv1.SearchOrganizationReportsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchOrganizationReportsRequest, ...client.CallOption) *reportv1.SearchOrganizationReportsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.SearchOrganizationReportsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.SearchOrganizationReportsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchOrganizationReportsCount provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) SearchOrganizationReportsCount(ctx context.Context, in *reportv1.SearchOrganizationReportsCountRequest, opts ...client.CallOption) (*reportv1.SearchOrganizationReportsCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.SearchOrganizationReportsCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchOrganizationReportsCountRequest, ...client.CallOption) (*reportv1.SearchOrganizationReportsCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchOrganizationReportsCountRequest, ...client.CallOption) *reportv1.SearchOrganizationReportsCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.SearchOrganizationReportsCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.SearchOrganizationReportsCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchReports provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) SearchReports(ctx context.Context, in *reportv1.SearchReportsRequest, opts ...client.CallOption) (*reportv1.SearchReportsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.SearchReportsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchReportsRequest, ...client.CallOption) (*reportv1.SearchReportsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchReportsRequest, ...client.CallOption) *reportv1.SearchReportsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.SearchReportsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.SearchReportsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchStaffReports provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) SearchStaffReports(ctx context.Context, in *reportv1.SearchStaffReportsRequest, opts ...client.CallOption) (*reportv1.SearchStaffReportsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.SearchStaffReportsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchStaffReportsRequest, ...client.CallOption) (*reportv1.SearchStaffReportsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchStaffReportsRequest, ...client.CallOption) *reportv1.SearchStaffReportsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.SearchStaffReportsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.SearchStaffReportsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchStaffReportsCount provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) SearchStaffReportsCount(ctx context.Context, in *reportv1.SearchStaffReportsCountRequest, opts ...client.CallOption) (*reportv1.SearchStaffReportsCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.SearchStaffReportsCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchStaffReportsCountRequest, ...client.CallOption) (*reportv1.SearchStaffReportsCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SearchStaffReportsCountRequest, ...client.CallOption) *reportv1.SearchStaffReportsCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.SearchStaffReportsCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.SearchStaffReportsCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitPulseTest provides a mock function with given fields: ctx, in, opts
func (_m *ReportAPIService) SubmitPulseTest(ctx context.Context, in *reportv1.SubmitPulseTestRequest, opts ...client.CallOption) (*reportv1.SubmitPulseTestResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reportv1.SubmitPulseTestResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SubmitPulseTestRequest, ...client.CallOption) (*reportv1.SubmitPulseTestResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reportv1.SubmitPulseTestRequest, ...client.CallOption) *reportv1.SubmitPulseTestResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reportv1.SubmitPulseTestResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reportv1.SubmitPulseTestRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportAPIService creates a new instance of ReportAPIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportAPIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportAPIService {
	mock := &ReportAPIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
