// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "go-micro.dev/v4/client"

	mock "github.com/stretchr/testify/mock"

	reviewv1 "github.com/jinmukeji/huimaibao-proto/gen/go/huimaibao/biz/review/v1"
)

// ReviewAPIService is an autogenerated mock type for the ReviewAPIService type
type ReviewAPIService struct {
	mock.Mock
}

// AcceptReviewIssue provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) AcceptReviewIssue(ctx context.Context, in *reviewv1.AcceptReviewIssueRequest, opts ...client.CallOption) (*reviewv1.AcceptReviewIssueResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.AcceptReviewIssueResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.AcceptReviewIssueRequest, ...client.CallOption) (*reviewv1.AcceptReviewIssueResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.AcceptReviewIssueRequest, ...client.CallOption) *reviewv1.AcceptReviewIssueResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.AcceptReviewIssueResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.AcceptReviewIssueRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelTreatmentReview provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) CancelTreatmentReview(ctx context.Context, in *reviewv1.CancelTreatmentReviewRequest, opts ...client.CallOption) (*reviewv1.CancelTreatmentReviewResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.CancelTreatmentReviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.CancelTreatmentReviewRequest, ...client.CallOption) (*reviewv1.CancelTreatmentReviewResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.CancelTreatmentReviewRequest, ...client.CallOption) *reviewv1.CancelTreatmentReviewResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.CancelTreatmentReviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.CancelTreatmentReviewRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitCertificateReviewResult provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) CommitCertificateReviewResult(ctx context.Context, in *reviewv1.CommitCertificateReviewResultRequest, opts ...client.CallOption) (*reviewv1.CommitCertificateReviewResultResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.CommitCertificateReviewResultResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.CommitCertificateReviewResultRequest, ...client.CallOption) (*reviewv1.CommitCertificateReviewResultResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.CommitCertificateReviewResultRequest, ...client.CallOption) *reviewv1.CommitCertificateReviewResultResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.CommitCertificateReviewResultResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.CommitCertificateReviewResultRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitEntityCertificate provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) CommitEntityCertificate(ctx context.Context, in *reviewv1.CommitEntityCertificateRequest, opts ...client.CallOption) (*reviewv1.CommitEntityCertificateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.CommitEntityCertificateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.CommitEntityCertificateRequest, ...client.CallOption) (*reviewv1.CommitEntityCertificateResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.CommitEntityCertificateRequest, ...client.CallOption) *reviewv1.CommitEntityCertificateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.CommitEntityCertificateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.CommitEntityCertificateRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitTreatmentReviewResult provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) CommitTreatmentReviewResult(ctx context.Context, in *reviewv1.CommitTreatmentReviewResultRequest, opts ...client.CallOption) (*reviewv1.CommitTreatmentReviewResultResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.CommitTreatmentReviewResultResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.CommitTreatmentReviewResultRequest, ...client.CallOption) (*reviewv1.CommitTreatmentReviewResultResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.CommitTreatmentReviewResultRequest, ...client.CallOption) *reviewv1.CommitTreatmentReviewResultResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.CommitTreatmentReviewResultResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.CommitTreatmentReviewResultRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfirmReviewNotification provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) ConfirmReviewNotification(ctx context.Context, in *reviewv1.ConfirmReviewNotificationRequest, opts ...client.CallOption) (*reviewv1.ConfirmReviewNotificationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.ConfirmReviewNotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ConfirmReviewNotificationRequest, ...client.CallOption) (*reviewv1.ConfirmReviewNotificationResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ConfirmReviewNotificationRequest, ...client.CallOption) *reviewv1.ConfirmReviewNotificationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.ConfirmReviewNotificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.ConfirmReviewNotificationRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewDetails provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) GetReviewDetails(ctx context.Context, in *reviewv1.GetReviewDetailsRequest, opts ...client.CallOption) (*reviewv1.GetReviewDetailsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.GetReviewDetailsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.GetReviewDetailsRequest, ...client.CallOption) (*reviewv1.GetReviewDetailsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.GetReviewDetailsRequest, ...client.CallOption) *reviewv1.GetReviewDetailsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.GetReviewDetailsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.GetReviewDetailsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewIssueDetails provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) GetReviewIssueDetails(ctx context.Context, in *reviewv1.GetReviewIssueDetailsRequest, opts ...client.CallOption) (*reviewv1.GetReviewIssueDetailsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.GetReviewIssueDetailsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.GetReviewIssueDetailsRequest, ...client.CallOption) (*reviewv1.GetReviewIssueDetailsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.GetReviewIssueDetailsRequest, ...client.CallOption) *reviewv1.GetReviewIssueDetailsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.GetReviewIssueDetailsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.GetReviewIssueDetailsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReviewResultByTargetId provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) GetReviewResultByTargetId(ctx context.Context, in *reviewv1.GetReviewResultByTargetIdRequest, opts ...client.CallOption) (*reviewv1.GetReviewResultByTargetIdResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.GetReviewResultByTargetIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.GetReviewResultByTargetIdRequest, ...client.CallOption) (*reviewv1.GetReviewResultByTargetIdResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.GetReviewResultByTargetIdRequest, ...client.CallOption) *reviewv1.GetReviewResultByTargetIdResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.GetReviewResultByTargetIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.GetReviewResultByTargetIdRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCertificateReviewStatus provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) ListCertificateReviewStatus(ctx context.Context, in *reviewv1.ListCertificateReviewStatusRequest, opts ...client.CallOption) (*reviewv1.ListCertificateReviewStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.ListCertificateReviewStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ListCertificateReviewStatusRequest, ...client.CallOption) (*reviewv1.ListCertificateReviewStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ListCertificateReviewStatusRequest, ...client.CallOption) *reviewv1.ListCertificateReviewStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.ListCertificateReviewStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.ListCertificateReviewStatusRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListReviewIssues provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) ListReviewIssues(ctx context.Context, in *reviewv1.ListReviewIssuesRequest, opts ...client.CallOption) (*reviewv1.ListReviewIssuesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.ListReviewIssuesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ListReviewIssuesRequest, ...client.CallOption) (*reviewv1.ListReviewIssuesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ListReviewIssuesRequest, ...client.CallOption) *reviewv1.ListReviewIssuesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.ListReviewIssuesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.ListReviewIssuesRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListReviewNotifications provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) ListReviewNotifications(ctx context.Context, in *reviewv1.ListReviewNotificationsRequest, opts ...client.CallOption) (*reviewv1.ListReviewNotificationsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.ListReviewNotificationsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ListReviewNotificationsRequest, ...client.CallOption) (*reviewv1.ListReviewNotificationsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ListReviewNotificationsRequest, ...client.CallOption) *reviewv1.ListReviewNotificationsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.ListReviewNotificationsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.ListReviewNotificationsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListReviewResultByTargetIds provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) ListReviewResultByTargetIds(ctx context.Context, in *reviewv1.ListReviewResultByTargetIdsRequest, opts ...client.CallOption) (*reviewv1.ListReviewResultByTargetIdsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.ListReviewResultByTargetIdsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ListReviewResultByTargetIdsRequest, ...client.CallOption) (*reviewv1.ListReviewResultByTargetIdsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.ListReviewResultByTargetIdsRequest, ...client.CallOption) *reviewv1.ListReviewResultByTargetIdsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.ListReviewResultByTargetIdsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.ListReviewResultByTargetIdsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitTreatmentToReview provides a mock function with given fields: ctx, in, opts
func (_m *ReviewAPIService) SubmitTreatmentToReview(ctx context.Context, in *reviewv1.SubmitTreatmentToReviewRequest, opts ...client.CallOption) (*reviewv1.SubmitTreatmentToReviewResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *reviewv1.SubmitTreatmentToReviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.SubmitTreatmentToReviewRequest, ...client.CallOption) (*reviewv1.SubmitTreatmentToReviewResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reviewv1.SubmitTreatmentToReviewRequest, ...client.CallOption) *reviewv1.SubmitTreatmentToReviewResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reviewv1.SubmitTreatmentToReviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reviewv1.SubmitTreatmentToReviewRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReviewAPIService creates a new instance of ReviewAPIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewAPIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewAPIService {
	mock := &ReviewAPIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
