package main

import (
	"flag"
	"log"
	"os"
	"text/template"

	plugins "github.com/jinmukeji/huimaibao-service/svc/summary"
	"gopkg.in/yaml.v2"
)

var (
	cfgFile, outFile, pkgName string
)

func main() {
	flag.StringVar(&cfgFile, "c", "errors.yml", "The error configuration file used to generate go file.")
	flag.StringVar(&outFile, "o", "error.gen.go", "The output go filepath.")
	flag.StringVar(&pkgName, "p", "example", "The go package name.")
	flag.Parse()

	// 读取 error 配置文件
	data, _ := os.ReadFile(cfgFile)
	var doc physiqueDoc
	doc.PkgName = pkgName
	err := yaml.Unmarshal(data, &(doc.Physiques))
	die(err)

	// 写入目标 go 文件
	f, err := os.Create(outFile)
	die(err)
	defer f.Close()

	err = errorTemplate.Execute(f, doc)
	die(err)
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

type physiqueDoc struct {
	PkgName   string
	Physiques map[string]plugins.Physique
}

var errorTemplate = template.Must(template.New("").Parse(`// Code generated by go generate. DO NOT EDIT.

package {{.PkgName}}

var (
    // 体质映射
    PhysiqueMap = map[string]Physique{
		{{- range $k,$physique := .Physiques}}
		{{$physique.CommentLine}}
        {{$k | printf "%q"}}:{
            Label: {{$physique.Label | printf "%q"}},
        },
        {{- end }}
    }
)

`))
