//管理员用户表
export const admin = [
    {
        path:'/',
        name:'general',
        component:()=>import('@/views/admin/GeneralizeView.vue'),
        meta:{
            title:'概况'
        }
    },
    {
        path:'/merchantManagement',
        name:'merchantManagement',
        component:()=>import('@/views/admin/MerchantView.vue'),
        meta:{
            title:'商户管理'
        },
        children:[
            {
                path:'',
                name:'commmange',
                component:()=>import('@/views/Commercialowner/CommermanageView.vue'),
            },
            {
                path:'prepayment',
                name:'prepayment',
                component:()=>import('@/views/Commercialowner/PrepaymentView.vue'),
            }
        ]
    },
    {
        path:'/products',
        name:'products',
        component:()=>import('@/views/admin/MemberView.vue'),
        meta:{
            title:'商品管理'
        },
        children:[
            {
                path:'',
                name:'commduse',
                component:()=>import('@/views/commodmanag/commoduseView.vue'),
                meta:{
                    title:'商品管理'
                },
            },
            {
                path:'addProduct',
                name:'addProduct',
                component:()=>import('@/views/commodmanag/addgoodsView.vue'),
                meta:{
                    title:'添加商品'
                },
            },
            {
                path:'edlgoods',
                name:'edlgoods',
                component:()=>import('@/views/commodmanag/editorialgoodsView.vue'),
                meta:{
                    title:'编辑商品'
                },
            },
            {
                path:'prodetails',
                name:'prodetails',
                component:()=>import('@/views/commodmanag/productdetailsView.vue'),
                meta:{
                    title:'编辑商品'
                },
            },
            {
                path:'dataanalysis',
                name:'dataanalysis',
                component:()=>import('@/views/commodmanag/DataanalysisView.vue'),
                meta:{
                    title:'编辑商品'
                },
            }
            
        ]
    },
    {
        path:'/recommendedProposal',
        name:'recommendedProposal',
        component:()=>import('@/views/admin/MembershipView.vue'),
        meta:{
            title:'商品推荐方案'
        },
        
        children:[
            {
                path:'',
                name:'Recomscheme',
                component:()=>import('@/views/productoption/RecomschemeView.vue'),
                
            },
            
            {
                path:'detailsView',
                name:'detailsView',
                component:()=>import('@/views/productoption/detailsView.vue'),
                meta:{
                    title:'详情'
                },
            },
            {
                path:'treatmentEdit',
                name:'treatmentEdit',
                component:()=>import('@/views/productoption/createschemeView.vue'),
                meta:{
                    title:'添加方案'
                },
            },
        ]
    },
    {
        path:'/billList',
        name:'billList',
        component:()=>import('@/views/admin/CheckView.vue'),
        meta:{
            title:'账单管理'
        },
        children:[
            {
                path:'',
                name:'checkdetai',
                component:()=>import('@/views/check/checkdetailView.vue'),
                meta:{
                    title:'账单详情'
                },
            },
            {
                path:'check',
                name:'check',
                component:()=>import('@/views/check/checkmanageView.vue'),
                meta:{
                    title:'账单详情'
                },
            }
        ]
    },
]

