// Code generated by go generate. DO NOT EDIT.

package summary

var (
	// 疾病映射
	RiskMap = map[string]Risk{
		// 血糖
		"JB0001": {
			Label: "血糖",
		},
		// 血压
		"JB0002": {
			Label: "血压",
		},
		// 血脂
		"JB0003": {
			Label: "血脂",
		},
		// 脊柱不正
		"JB0005": {
			Label: "脊柱不正",
		},
		// 焦虑
		"JB0006": {
			Label: "焦虑",
		},
		// 颈椎病
		"JB0007": {
			Label: "颈椎病",
		},
		// 咽炎
		"JB0008": {
			Label: "咽炎",
		},
		// 脑供血不足
		"JB0011": {
			Label: "脑供血不足",
		},
		// 免疫力
		"JB0012": {
			Label: "免疫力",
		},
		// 疲劳
		"JB0013": {
			Label: "疲劳",
		},
		// 肾功能减退
		"JB0014": {
			Label: "肾功能减退",
		},
		// 心梗
		"JB0015": {
			Label: "心梗",
		},
		// 抑郁
		"JB0016": {
			Label: "抑郁",
		},
		// 睡眠
		"JB0017": {
			Label: "睡眠",
		},
		// 胃动力不足
		"JB0018": {
			Label: "胃动力不足",
		},
		// 胃炎
		"JB0019": {
			Label: "胃炎",
		},
	}
)
