// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "go-micro.dev/v4/client"

	customerv1 "github.com/jinmukeji/huimaibao-proto/gen/go/huimaibao/biz/customer/v1"
	mock "github.com/stretchr/testify/mock"
)

// CustomerAPIService is an autogenerated mock type for the CustomerAPIService type
type CustomerAPIService struct {
	mock.Mock
}

// AddCustomer provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) AddCustomer(ctx context.Context, in *customerv1.AddCustomerRequest, opts ...client.CallOption) (*customerv1.AddCustomerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.AddCustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.AddCustomerRequest, ...client.CallOption) (*customerv1.AddCustomerResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.AddCustomerRequest, ...client.CallOption) *customerv1.AddCustomerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.AddCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.AddCustomerRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BatchGetCustomersByIds provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) BatchGetCustomersByIds(ctx context.Context, in *customerv1.BatchGetCustomersByIdsRequest, opts ...client.CallOption) (*customerv1.BatchGetCustomersByIdsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.BatchGetCustomersByIdsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.BatchGetCustomersByIdsRequest, ...client.CallOption) (*customerv1.BatchGetCustomersByIdsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.BatchGetCustomersByIdsRequest, ...client.CallOption) *customerv1.BatchGetCustomersByIdsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.BatchGetCustomersByIdsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.BatchGetCustomersByIdsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckCustomerExist provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) CheckCustomerExist(ctx context.Context, in *customerv1.CheckCustomerExistRequest, opts ...client.CallOption) (*customerv1.CheckCustomerExistResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.CheckCustomerExistResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.CheckCustomerExistRequest, ...client.CallOption) (*customerv1.CheckCustomerExistResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.CheckCustomerExistRequest, ...client.CallOption) *customerv1.CheckCustomerExistResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.CheckCustomerExistResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.CheckCustomerExistRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCustomer provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) DeleteCustomer(ctx context.Context, in *customerv1.DeleteCustomerRequest, opts ...client.CallOption) (*customerv1.DeleteCustomerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.DeleteCustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.DeleteCustomerRequest, ...client.CallOption) (*customerv1.DeleteCustomerResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.DeleteCustomerRequest, ...client.CallOption) *customerv1.DeleteCustomerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.DeleteCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.DeleteCustomerRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomer provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) GetCustomer(ctx context.Context, in *customerv1.GetCustomerRequest, opts ...client.CallOption) (*customerv1.GetCustomerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.GetCustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetCustomerRequest, ...client.CallOption) (*customerv1.GetCustomerResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetCustomerRequest, ...client.CallOption) *customerv1.GetCustomerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.GetCustomerRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerCount provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) GetCustomerCount(ctx context.Context, in *customerv1.GetCustomerCountRequest, opts ...client.CallOption) (*customerv1.GetCustomerCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.GetCustomerCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetCustomerCountRequest, ...client.CallOption) (*customerv1.GetCustomerCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetCustomerCountRequest, ...client.CallOption) *customerv1.GetCustomerCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetCustomerCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.GetCustomerCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEntityCustomerCompareSummary provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) GetEntityCustomerCompareSummary(ctx context.Context, in *customerv1.GetEntityCustomerCompareSummaryRequest, opts ...client.CallOption) (*customerv1.GetEntityCustomerCompareSummaryResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.GetEntityCustomerCompareSummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetEntityCustomerCompareSummaryRequest, ...client.CallOption) (*customerv1.GetEntityCustomerCompareSummaryResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetEntityCustomerCompareSummaryRequest, ...client.CallOption) *customerv1.GetEntityCustomerCompareSummaryResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetEntityCustomerCompareSummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.GetEntityCustomerCompareSummaryRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationCustomerCompareSummary provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) GetOrganizationCustomerCompareSummary(ctx context.Context, in *customerv1.GetOrganizationCustomerCompareSummaryRequest, opts ...client.CallOption) (*customerv1.GetOrganizationCustomerCompareSummaryResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.GetOrganizationCustomerCompareSummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetOrganizationCustomerCompareSummaryRequest, ...client.CallOption) (*customerv1.GetOrganizationCustomerCompareSummaryResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetOrganizationCustomerCompareSummaryRequest, ...client.CallOption) *customerv1.GetOrganizationCustomerCompareSummaryResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetOrganizationCustomerCompareSummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.GetOrganizationCustomerCompareSummaryRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationCustomerCount provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) GetOrganizationCustomerCount(ctx context.Context, in *customerv1.GetOrganizationCustomerCountRequest, opts ...client.CallOption) (*customerv1.GetOrganizationCustomerCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.GetOrganizationCustomerCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetOrganizationCustomerCountRequest, ...client.CallOption) (*customerv1.GetOrganizationCustomerCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetOrganizationCustomerCountRequest, ...client.CallOption) *customerv1.GetOrganizationCustomerCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetOrganizationCustomerCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.GetOrganizationCustomerCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationOverdueCount provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) GetOrganizationOverdueCount(ctx context.Context, in *customerv1.GetOrganizationOverdueCountRequest, opts ...client.CallOption) (*customerv1.GetOrganizationOverdueCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.GetOrganizationOverdueCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetOrganizationOverdueCountRequest, ...client.CallOption) (*customerv1.GetOrganizationOverdueCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetOrganizationOverdueCountRequest, ...client.CallOption) *customerv1.GetOrganizationOverdueCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetOrganizationOverdueCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.GetOrganizationOverdueCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOverdueCount provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) GetOverdueCount(ctx context.Context, in *customerv1.GetOverdueCountRequest, opts ...client.CallOption) (*customerv1.GetOverdueCountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.GetOverdueCountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetOverdueCountRequest, ...client.CallOption) (*customerv1.GetOverdueCountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetOverdueCountRequest, ...client.CallOption) *customerv1.GetOverdueCountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetOverdueCountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.GetOverdueCountRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTenantsCustomerRank provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) GetTenantsCustomerRank(ctx context.Context, in *customerv1.GetTenantsCustomerRankRequest, opts ...client.CallOption) (*customerv1.GetTenantsCustomerRankResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.GetTenantsCustomerRankResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetTenantsCustomerRankRequest, ...client.CallOption) (*customerv1.GetTenantsCustomerRankResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.GetTenantsCustomerRankRequest, ...client.CallOption) *customerv1.GetTenantsCustomerRankResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetTenantsCustomerRankResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.GetTenantsCustomerRankRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCustomers provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) ListCustomers(ctx context.Context, in *customerv1.ListCustomersRequest, opts ...client.CallOption) (*customerv1.ListCustomersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.ListCustomersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.ListCustomersRequest, ...client.CallOption) (*customerv1.ListCustomersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.ListCustomersRequest, ...client.CallOption) *customerv1.ListCustomersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.ListCustomersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.ListCustomersRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchAppCustomerLastStatus provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) SearchAppCustomerLastStatus(ctx context.Context, in *customerv1.SearchAppCustomerLastStatusRequest, opts ...client.CallOption) (*customerv1.SearchAppCustomerLastStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.SearchAppCustomerLastStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchAppCustomerLastStatusRequest, ...client.CallOption) (*customerv1.SearchAppCustomerLastStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchAppCustomerLastStatusRequest, ...client.CallOption) *customerv1.SearchAppCustomerLastStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.SearchAppCustomerLastStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.SearchAppCustomerLastStatusRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCustomerIDByCustomerInfo provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) SearchCustomerIDByCustomerInfo(ctx context.Context, in *customerv1.SearchCustomerIDByCustomerInfoRequest, opts ...client.CallOption) (*customerv1.SearchCustomerIDByCustomerInfoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.SearchCustomerIDByCustomerInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchCustomerIDByCustomerInfoRequest, ...client.CallOption) (*customerv1.SearchCustomerIDByCustomerInfoResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchCustomerIDByCustomerInfoRequest, ...client.CallOption) *customerv1.SearchCustomerIDByCustomerInfoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.SearchCustomerIDByCustomerInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.SearchCustomerIDByCustomerInfoRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCustomerLastStatus provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) SearchCustomerLastStatus(ctx context.Context, in *customerv1.SearchCustomerLastStatusRequest, opts ...client.CallOption) (*customerv1.SearchCustomerLastStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.SearchCustomerLastStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchCustomerLastStatusRequest, ...client.CallOption) (*customerv1.SearchCustomerLastStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchCustomerLastStatusRequest, ...client.CallOption) *customerv1.SearchCustomerLastStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.SearchCustomerLastStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.SearchCustomerLastStatusRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCustomers provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) SearchCustomers(ctx context.Context, in *customerv1.SearchCustomersRequest, opts ...client.CallOption) (*customerv1.SearchCustomersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.SearchCustomersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchCustomersRequest, ...client.CallOption) (*customerv1.SearchCustomersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchCustomersRequest, ...client.CallOption) *customerv1.SearchCustomersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.SearchCustomersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.SearchCustomersRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchOrganizationCustomerLastStatus provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) SearchOrganizationCustomerLastStatus(ctx context.Context, in *customerv1.SearchOrganizationCustomerLastStatusRequest, opts ...client.CallOption) (*customerv1.SearchOrganizationCustomerLastStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.SearchOrganizationCustomerLastStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchOrganizationCustomerLastStatusRequest, ...client.CallOption) (*customerv1.SearchOrganizationCustomerLastStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchOrganizationCustomerLastStatusRequest, ...client.CallOption) *customerv1.SearchOrganizationCustomerLastStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.SearchOrganizationCustomerLastStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.SearchOrganizationCustomerLastStatusRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchOrganizationTenantCompare provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) SearchOrganizationTenantCompare(ctx context.Context, in *customerv1.SearchOrganizationTenantCompareRequest, opts ...client.CallOption) (*customerv1.SearchOrganizationTenantCompareResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.SearchOrganizationTenantCompareResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchOrganizationTenantCompareRequest, ...client.CallOption) (*customerv1.SearchOrganizationTenantCompareResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchOrganizationTenantCompareRequest, ...client.CallOption) *customerv1.SearchOrganizationTenantCompareResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.SearchOrganizationTenantCompareResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.SearchOrganizationTenantCompareRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchOverdueCustomers provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) SearchOverdueCustomers(ctx context.Context, in *customerv1.SearchOverdueCustomersRequest, opts ...client.CallOption) (*customerv1.SearchOverdueCustomersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.SearchOverdueCustomersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchOverdueCustomersRequest, ...client.CallOption) (*customerv1.SearchOverdueCustomersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.SearchOverdueCustomersRequest, ...client.CallOption) *customerv1.SearchOverdueCustomersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.SearchOverdueCustomersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.SearchOverdueCustomersRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCustomer provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) UpdateCustomer(ctx context.Context, in *customerv1.UpdateCustomerRequest, opts ...client.CallOption) (*customerv1.UpdateCustomerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.UpdateCustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.UpdateCustomerRequest, ...client.CallOption) (*customerv1.UpdateCustomerResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.UpdateCustomerRequest, ...client.CallOption) *customerv1.UpdateCustomerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.UpdateCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.UpdateCustomerRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCustomerLastStatus provides a mock function with given fields: ctx, in, opts
func (_m *CustomerAPIService) UpdateCustomerLastStatus(ctx context.Context, in *customerv1.UpdateCustomerLastStatusRequest, opts ...client.CallOption) (*customerv1.UpdateCustomerLastStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *customerv1.UpdateCustomerLastStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.UpdateCustomerLastStatusRequest, ...client.CallOption) (*customerv1.UpdateCustomerLastStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *customerv1.UpdateCustomerLastStatusRequest, ...client.CallOption) *customerv1.UpdateCustomerLastStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.UpdateCustomerLastStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *customerv1.UpdateCustomerLastStatusRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerAPIService creates a new instance of CustomerAPIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerAPIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerAPIService {
	mock := &CustomerAPIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
