// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FileStore is an autogenerated mock type for the FileStore type
type FileStore struct {
	mock.Mock
}

// Save provides a mock function with given fields: path, mime, content
func (_m *FileStore) Save(path string, mime string, content io.ReadSeeker) (string, error) {
	ret := _m.Called(path, mime, content)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, io.ReadSeeker) (string, error)); ok {
		return rf(path, mime, content)
	}
	if rf, ok := ret.Get(0).(func(string, string, io.ReadSeeker) string); ok {
		r0 = rf(path, mime, content)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, io.ReadSeeker) error); ok {
		r1 = rf(path, mime, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFileStore creates a new instance of FileStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileStore {
	mock := &FileStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
