package main

import (
	"flag"
	"log"
	"os"
	"text/template"

	plugins "github.com/jinmukeji/huimaibao-service/svc/summary"
	"gopkg.in/yaml.v2"
)

var (
	cfgFile, outFile, pkgName string
)

func main() {
	flag.StringVar(&cfgFile, "c", "errors.yml", "The error configuration file used to generate go file.")
	flag.StringVar(&outFile, "o", "error.gen.go", "The output go filepath.")
	flag.StringVar(&pkgName, "p", "example", "The go package name.")
	flag.Parse()

	// 读取 error 配置文件
	data, _ := os.ReadFile(cfgFile)
	var doc summaryDoc
	doc.PkgName = pkgName
	err := yaml.Unmarshal(data, &(doc.Summaries))
	die(err)

	// 写入目标 go 文件
	f, err := os.Create(outFile)
	die(err)
	defer f.Close()

	err = errorTemplate.Execute(f, doc)
	die(err)
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

type summaryDoc struct {
	PkgName   string
	Summaries map[string]plugins.Summary
}

var errorTemplate = template.Must(template.New("").Parse(`// Code generated by go generate. DO NOT EDIT.

package {{.PkgName}}

var (
    // 中医报告小结
    DirtyDialectSummary = map[string]Summary{
		{{- range $k,$summary := .Summaries}}
		{{$summary.CommentLine}}
        {{$k | printf "%q"}}:{
            Label: {{$summary.Label | printf "%q"}},
            Summary: {{$summary.Summary | printf "%q"}},
        },
        {{- end }}
    }
)

`))
