// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "go-micro.dev/v4/client"

	mock "github.com/stretchr/testify/mock"

	productv1 "github.com/jinmukeji/huimaibao-proto/gen/go/huimaibao/biz/product/v1"
)

// ProductAPIService is an autogenerated mock type for the ProductAPIService type
type ProductAPIService struct {
	mock.Mock
}

// CancelTreatmentReview provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) CancelTreatmentReview(ctx context.Context, in *productv1.CancelTreatmentReviewRequest, opts ...client.CallOption) (*productv1.CancelTreatmentReviewResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.CancelTreatmentReviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.CancelTreatmentReviewRequest, ...client.CallOption) (*productv1.CancelTreatmentReviewResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.CancelTreatmentReviewRequest, ...client.CallOption) *productv1.CancelTreatmentReviewResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.CancelTreatmentReviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.CancelTreatmentReviewRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangeProductStatusByTreatmentRevId provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) ChangeProductStatusByTreatmentRevId(ctx context.Context, in *productv1.ChangeProductStatusByTreatmentRevIdRequest, opts ...client.CallOption) (*productv1.ChangeProductStatusByTreatmentRevIdResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.ChangeProductStatusByTreatmentRevIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ChangeProductStatusByTreatmentRevIdRequest, ...client.CallOption) (*productv1.ChangeProductStatusByTreatmentRevIdResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ChangeProductStatusByTreatmentRevIdRequest, ...client.CallOption) *productv1.ChangeProductStatusByTreatmentRevIdResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.ChangeProductStatusByTreatmentRevIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.ChangeProductStatusByTreatmentRevIdRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangeTreatmentRevStatus provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) ChangeTreatmentRevStatus(ctx context.Context, in *productv1.ChangeTreatmentRevStatusRequest, opts ...client.CallOption) (*productv1.ChangeTreatmentRevStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.ChangeTreatmentRevStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ChangeTreatmentRevStatusRequest, ...client.CallOption) (*productv1.ChangeTreatmentRevStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ChangeTreatmentRevStatusRequest, ...client.CallOption) *productv1.ChangeTreatmentRevStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.ChangeTreatmentRevStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.ChangeTreatmentRevStatusRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) CreateProduct(ctx context.Context, in *productv1.CreateProductRequest, opts ...client.CallOption) (*productv1.CreateProductResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.CreateProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.CreateProductRequest, ...client.CallOption) (*productv1.CreateProductResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.CreateProductRequest, ...client.CallOption) *productv1.CreateProductResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.CreateProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.CreateProductRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTreatment provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) CreateTreatment(ctx context.Context, in *productv1.CreateTreatmentRequest, opts ...client.CallOption) (*productv1.CreateTreatmentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.CreateTreatmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.CreateTreatmentRequest, ...client.CallOption) (*productv1.CreateTreatmentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.CreateTreatmentRequest, ...client.CallOption) *productv1.CreateTreatmentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.CreateTreatmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.CreateTreatmentRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) DeleteProduct(ctx context.Context, in *productv1.DeleteProductRequest, opts ...client.CallOption) (*productv1.DeleteProductResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.DeleteProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.DeleteProductRequest, ...client.CallOption) (*productv1.DeleteProductResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.DeleteProductRequest, ...client.CallOption) *productv1.DeleteProductResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.DeleteProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.DeleteProductRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTreatment provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) DeleteTreatment(ctx context.Context, in *productv1.DeleteTreatmentRequest, opts ...client.CallOption) (*productv1.DeleteTreatmentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.DeleteTreatmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.DeleteTreatmentRequest, ...client.CallOption) (*productv1.DeleteTreatmentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.DeleteTreatmentRequest, ...client.CallOption) *productv1.DeleteTreatmentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.DeleteTreatmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.DeleteTreatmentRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) GetProduct(ctx context.Context, in *productv1.GetProductRequest, opts ...client.CallOption) (*productv1.GetProductResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.GetProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.GetProductRequest, ...client.CallOption) (*productv1.GetProductResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.GetProductRequest, ...client.CallOption) *productv1.GetProductResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.GetProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.GetProductRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductStatistics provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) GetProductStatistics(ctx context.Context, in *productv1.GetProductStatisticsRequest, opts ...client.CallOption) (*productv1.GetProductStatisticsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.GetProductStatisticsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.GetProductStatisticsRequest, ...client.CallOption) (*productv1.GetProductStatisticsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.GetProductStatisticsRequest, ...client.CallOption) *productv1.GetProductStatisticsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.GetProductStatisticsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.GetProductStatisticsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTreatment provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) GetTreatment(ctx context.Context, in *productv1.GetTreatmentRequest, opts ...client.CallOption) (*productv1.GetTreatmentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.GetTreatmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.GetTreatmentRequest, ...client.CallOption) (*productv1.GetTreatmentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.GetTreatmentRequest, ...client.CallOption) *productv1.GetTreatmentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.GetTreatmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.GetTreatmentRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTreatmentRevByTreatmentRevId provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) GetTreatmentRevByTreatmentRevId(ctx context.Context, in *productv1.GetTreatmentRevByTreatmentRevIdRequest, opts ...client.CallOption) (*productv1.GetTreatmentRevByTreatmentRevIdResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.GetTreatmentRevByTreatmentRevIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.GetTreatmentRevByTreatmentRevIdRequest, ...client.CallOption) (*productv1.GetTreatmentRevByTreatmentRevIdResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.GetTreatmentRevByTreatmentRevIdRequest, ...client.CallOption) *productv1.GetTreatmentRevByTreatmentRevIdResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.GetTreatmentRevByTreatmentRevIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.GetTreatmentRevByTreatmentRevIdRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProducts provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) ListProducts(ctx context.Context, in *productv1.ListProductsRequest, opts ...client.CallOption) (*productv1.ListProductsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.ListProductsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListProductsRequest, ...client.CallOption) (*productv1.ListProductsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListProductsRequest, ...client.CallOption) *productv1.ListProductsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.ListProductsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.ListProductsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRecommendedProducts provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) ListRecommendedProducts(ctx context.Context, in *productv1.ListRecommendedProductsRequest, opts ...client.CallOption) (*productv1.ListRecommendedProductsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.ListRecommendedProductsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListRecommendedProductsRequest, ...client.CallOption) (*productv1.ListRecommendedProductsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListRecommendedProductsRequest, ...client.CallOption) *productv1.ListRecommendedProductsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.ListRecommendedProductsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.ListRecommendedProductsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSymptomProducts provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) ListSymptomProducts(ctx context.Context, in *productv1.ListSymptomProductsRequest, opts ...client.CallOption) (*productv1.ListSymptomProductsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.ListSymptomProductsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListSymptomProductsRequest, ...client.CallOption) (*productv1.ListSymptomProductsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListSymptomProductsRequest, ...client.CallOption) *productv1.ListSymptomProductsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.ListSymptomProductsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.ListSymptomProductsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTreatmentNameByIds provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) ListTreatmentNameByIds(ctx context.Context, in *productv1.ListTreatmentNameByIdsRequest, opts ...client.CallOption) (*productv1.ListTreatmentNameByIdsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.ListTreatmentNameByIdsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListTreatmentNameByIdsRequest, ...client.CallOption) (*productv1.ListTreatmentNameByIdsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListTreatmentNameByIdsRequest, ...client.CallOption) *productv1.ListTreatmentNameByIdsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.ListTreatmentNameByIdsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.ListTreatmentNameByIdsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTreatments provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) ListTreatments(ctx context.Context, in *productv1.ListTreatmentsRequest, opts ...client.CallOption) (*productv1.ListTreatmentsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.ListTreatmentsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListTreatmentsRequest, ...client.CallOption) (*productv1.ListTreatmentsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.ListTreatmentsRequest, ...client.CallOption) *productv1.ListTreatmentsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.ListTreatmentsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.ListTreatmentsRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublishTreatment provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) PublishTreatment(ctx context.Context, in *productv1.PublishTreatmentRequest, opts ...client.CallOption) (*productv1.PublishTreatmentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.PublishTreatmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.PublishTreatmentRequest, ...client.CallOption) (*productv1.PublishTreatmentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.PublishTreatmentRequest, ...client.CallOption) *productv1.PublishTreatmentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.PublishTreatmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.PublishTreatmentRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveTreatment provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) RemoveTreatment(ctx context.Context, in *productv1.RemoveTreatmentRequest, opts ...client.CallOption) (*productv1.RemoveTreatmentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.RemoveTreatmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.RemoveTreatmentRequest, ...client.CallOption) (*productv1.RemoveTreatmentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.RemoveTreatmentRequest, ...client.CallOption) *productv1.RemoveTreatmentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.RemoveTreatmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.RemoveTreatmentRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitTreatmentToReview provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) SubmitTreatmentToReview(ctx context.Context, in *productv1.SubmitTreatmentToReviewRequest, opts ...client.CallOption) (*productv1.SubmitTreatmentToReviewResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.SubmitTreatmentToReviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.SubmitTreatmentToReviewRequest, ...client.CallOption) (*productv1.SubmitTreatmentToReviewResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.SubmitTreatmentToReviewRequest, ...client.CallOption) *productv1.SubmitTreatmentToReviewResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.SubmitTreatmentToReviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.SubmitTreatmentToReviewRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) UpdateProduct(ctx context.Context, in *productv1.UpdateProductRequest, opts ...client.CallOption) (*productv1.UpdateProductResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.UpdateProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.UpdateProductRequest, ...client.CallOption) (*productv1.UpdateProductResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.UpdateProductRequest, ...client.CallOption) *productv1.UpdateProductResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.UpdateProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.UpdateProductRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTreatment provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) UpdateTreatment(ctx context.Context, in *productv1.UpdateTreatmentRequest, opts ...client.CallOption) (*productv1.UpdateTreatmentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.UpdateTreatmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.UpdateTreatmentRequest, ...client.CallOption) (*productv1.UpdateTreatmentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.UpdateTreatmentRequest, ...client.CallOption) *productv1.UpdateTreatmentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.UpdateTreatmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.UpdateTreatmentRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTreatmentStatus provides a mock function with given fields: ctx, in, opts
func (_m *ProductAPIService) UpdateTreatmentStatus(ctx context.Context, in *productv1.UpdateTreatmentStatusRequest, opts ...client.CallOption) (*productv1.UpdateTreatmentStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *productv1.UpdateTreatmentStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.UpdateTreatmentStatusRequest, ...client.CallOption) (*productv1.UpdateTreatmentStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *productv1.UpdateTreatmentStatusRequest, ...client.CallOption) *productv1.UpdateTreatmentStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*productv1.UpdateTreatmentStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *productv1.UpdateTreatmentStatusRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductAPIService creates a new instance of ProductAPIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductAPIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductAPIService {
	mock := &ProductAPIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
