// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "go-micro.dev/v4/client"

	mock "github.com/stretchr/testify/mock"

	notificationv1 "github.com/jinmukeji/huimaibao-proto/gen/go/huimaibao/biz/notification/v1"
)

// NotificationAPIService is an autogenerated mock type for the NotificationAPIService type
type NotificationAPIService struct {
	mock.Mock
}

// CheckTxIdUsage provides a mock function with given fields: ctx, in, opts
func (_m *NotificationAPIService) CheckTxIdUsage(ctx context.Context, in *notificationv1.CheckTxIdUsageRequest, opts ...client.CallOption) (*notificationv1.CheckTxIdUsageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *notificationv1.CheckTxIdUsageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.CheckTxIdUsageRequest, ...client.CallOption) (*notificationv1.CheckTxIdUsageResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.CheckTxIdUsageRequest, ...client.CallOption) *notificationv1.CheckTxIdUsageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notificationv1.CheckTxIdUsageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notificationv1.CheckTxIdUsageRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestPhoneVerificationCode provides a mock function with given fields: ctx, in, opts
func (_m *NotificationAPIService) GetLatestPhoneVerificationCode(ctx context.Context, in *notificationv1.GetLatestPhoneVerificationCodeRequest, opts ...client.CallOption) (*notificationv1.GetLatestPhoneVerificationCodeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *notificationv1.GetLatestPhoneVerificationCodeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.GetLatestPhoneVerificationCodeRequest, ...client.CallOption) (*notificationv1.GetLatestPhoneVerificationCodeResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.GetLatestPhoneVerificationCodeRequest, ...client.CallOption) *notificationv1.GetLatestPhoneVerificationCodeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notificationv1.GetLatestPhoneVerificationCodeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notificationv1.GetLatestPhoneVerificationCodeRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendBillingNotification provides a mock function with given fields: ctx, in, opts
func (_m *NotificationAPIService) SendBillingNotification(ctx context.Context, in *notificationv1.SendBillingNotificationRequest, opts ...client.CallOption) (*notificationv1.SendBillingNotificationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *notificationv1.SendBillingNotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.SendBillingNotificationRequest, ...client.CallOption) (*notificationv1.SendBillingNotificationResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.SendBillingNotificationRequest, ...client.CallOption) *notificationv1.SendBillingNotificationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notificationv1.SendBillingNotificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notificationv1.SendBillingNotificationRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendReviewNotification provides a mock function with given fields: ctx, in, opts
func (_m *NotificationAPIService) SendReviewNotification(ctx context.Context, in *notificationv1.SendReviewNotificationRequest, opts ...client.CallOption) (*notificationv1.SendReviewNotificationResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *notificationv1.SendReviewNotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.SendReviewNotificationRequest, ...client.CallOption) (*notificationv1.SendReviewNotificationResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.SendReviewNotificationRequest, ...client.CallOption) *notificationv1.SendReviewNotificationResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notificationv1.SendReviewNotificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notificationv1.SendReviewNotificationRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendVerificationCode provides a mock function with given fields: ctx, in, opts
func (_m *NotificationAPIService) SendVerificationCode(ctx context.Context, in *notificationv1.SendVerificationCodeRequest, opts ...client.CallOption) (*notificationv1.SendVerificationCodeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *notificationv1.SendVerificationCodeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.SendVerificationCodeRequest, ...client.CallOption) (*notificationv1.SendVerificationCodeResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.SendVerificationCodeRequest, ...client.CallOption) *notificationv1.SendVerificationCodeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notificationv1.SendVerificationCodeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notificationv1.SendVerificationCodeRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyPhoneVerificationCode provides a mock function with given fields: ctx, in, opts
func (_m *NotificationAPIService) VerifyPhoneVerificationCode(ctx context.Context, in *notificationv1.VerifyPhoneVerificationCodeRequest, opts ...client.CallOption) (*notificationv1.VerifyPhoneVerificationCodeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *notificationv1.VerifyPhoneVerificationCodeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.VerifyPhoneVerificationCodeRequest, ...client.CallOption) (*notificationv1.VerifyPhoneVerificationCodeResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notificationv1.VerifyPhoneVerificationCodeRequest, ...client.CallOption) *notificationv1.VerifyPhoneVerificationCodeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notificationv1.VerifyPhoneVerificationCodeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notificationv1.VerifyPhoneVerificationCodeRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNotificationAPIService creates a new instance of NotificationAPIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationAPIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationAPIService {
	mock := &NotificationAPIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
