// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	client "github.com/jinmukeji/huimaibao-service/svc/notification/client"
	mock "github.com/stretchr/testify/mock"
)

// SmsSend is an autogenerated mock type for the SmsSend type
type SmsSend struct {
	mock.Mock
}

// SendNotification provides a mock function with given fields: phoneNumber, signName, templateAction, templateParam
func (_m *SmsSend) SendNotification(phoneNumber []string, signName string, templateAction client.TemplateAction, templateParam map[string]string) (bool, error) {
	ret := _m.Called(phoneNumber, signName, templateAction, templateParam)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, string, client.TemplateAction, map[string]string) (bool, error)); ok {
		return rf(phoneNumber, signName, templateAction, templateParam)
	}
	if rf, ok := ret.Get(0).(func([]string, string, client.TemplateAction, map[string]string) bool); ok {
		r0 = rf(phoneNumber, signName, templateAction, templateParam)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func([]string, string, client.TemplateAction, map[string]string) error); ok {
		r1 = rf(phoneNumber, signName, templateAction, templateParam)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendSms provides a mock function with given fields: phoneNumber, signName, templateAction, language, templateParam
func (_m *SmsSend) SendSms(phoneNumber string, signName string, templateAction client.TemplateAction, language client.TemplateLanguage, templateParam map[string]string) (bool, error) {
	ret := _m.Called(phoneNumber, signName, templateAction, language, templateParam)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, client.TemplateAction, client.TemplateLanguage, map[string]string) (bool, error)); ok {
		return rf(phoneNumber, signName, templateAction, language, templateParam)
	}
	if rf, ok := ret.Get(0).(func(string, string, client.TemplateAction, client.TemplateLanguage, map[string]string) bool); ok {
		r0 = rf(phoneNumber, signName, templateAction, language, templateParam)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, client.TemplateAction, client.TemplateLanguage, map[string]string) error); ok {
		r1 = rf(phoneNumber, signName, templateAction, language, templateParam)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSmsSend creates a new instance of SmsSend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSmsSend(t interface {
	mock.TestingT
	Cleanup(func())
}) *SmsSend {
	mock := &SmsSend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
