# 体质KEY
"T0001":
  label: "阳虚质（脉沉迟）"
"T0002":
  label: "阴虚质（脉细数）"
"T0003":
  label: "气虚质（脉弱）"
"T0004":
  label: "气郁质（脉弦）"
"T0005":
  label: "倾向气郁质（脉弦）"
"T0006":
  label: "倾向阴虚质（脉细数）"
"T0007":
  label: "平和倾向阳虚质（脉稍沉迟）"
"T0008":
  label: "接近平和质（脉稍平）"
"T0009":
  label: "倾向气虚质（脉稍弱）"
"T0010":
  label: "接近平和质（脉平稍数）"
"T0011":
  label: "接近平和质（脉平稍细）"
"T0012":
  label: "平和质"
"T0013":
  label: "痰湿质兼血瘀质（脉弦滑）"
"T0014":
  label: "痰湿质（脉滑）"
"T0015":
  label: "湿热质（脉滑数）"
"T0016":
  label: "血瘀质（脉涩）"
"T0017":
  label: "倾向气郁质（脉稍弦）"
"T0018":
  label: "倾向阴虚质（脉稍细数）"
"T0019":
  label: "倾向阳虚质（脉稍沉迟）"
"T0020":
  label: "平和倾向阴虚质（脉稍细数）"
"T0021":
  label: "阴虚质兼血瘀质（脉细数）"
"T0022":
  label: "阴虚质兼痰湿质（脉细数）"
"T0023":
  label: "阴虚质兼湿热质（脉细数）"
"T0024":
  label: "阴虚质兼气郁质（脉细数）"
"T0025":
  label: "阳虚质兼气郁质（脉沉涩）"
"T0026":
  label: "阳虚质（脉沉）"
"T0027":
  label: "阴虚质（脉细）"
"T0028":
  label: "倾向阴虚质（脉稍细）"
"T0029":
  label: "倾向阳虚质（脉稍沉）"
"T0030":
  label: "倾向阴虚质（脉细）"
"T0031":
  label: "平和倾向阳虚质（脉稍沉）"
"T0032":
  label: "平和倾向阴虚质（脉稍细）"
"T0033":
  label: "阴虚质兼血瘀质（脉细）"
"T0034":
  label: "阴虚质兼痰湿质（脉细）"
"T0035":
  label: "阴虚质兼湿热质（脉细）"
"T0036":
  label: "阴虚质兼气郁质（脉细）"
"T0037":
  label: "湿热质（脉滑）"
