# 中医报告小结
"Z0001":
  label: "心肾不交"
  summary: "心烦失寐，心悸不安，眩晕，耳鸣，健忘，五心烦热，咽干口燥，腰膝酸软，遗精带下。向下损耗肾水，失阴液濡养，或者过于用肾，则腰酸，头晕，健忘，手心热，咽干口燥等虚热热的表现。"
"Z0002":
  label: "肾阳虚"
  summary: "神疲乏力、精神不振、活力低下、易疲劳；畏寒怕冷、四肢发凉（重者夏天也凉）、身体发沉；腰膝酸痛、腰背冷痛、筋骨萎软；性功能减退、小便清长、余沥不尽、尿少或夜尿频多；听力下降或耳鸣；记忆力减退、嗜睡、多梦、自汗；易患腰痛、关节痛等；易患骨质疏松症、颈椎病、腰椎病等；须发易脱落、早白；形体虚胖或羸瘦；反映在面部则色青白无光或黧黑；"
"Z0003":
  label: "肾阴虚"
  summary: "临床表现主要有头晕耳鸣、腰膝酸痛、失眠多梦、潮热盗汗、五心烦热、咽干颧红、齿松发脱、形体消瘦、小便短黄或大便干结，男子兼见阳强易举、遗精、早泄，女子经少或经闭、崩漏等。"
"Z0004":
  label: "脾胃不调，胃火偏旺"
  summary: "脾胃的运化功能受阻所导致的脘腹痞满，呕恶，口苦纳呆，肢体困重，大便黏腻，小便短黄等症。常因外感湿热之邪，或者过食肥甘厚味，导致脾胃湿热蕴阻所致。因湿热内蕴中焦常见的疾病有：痞满，便秘，痢疾，黄疸等。"
"Z0005":
  label: "湿热困脾"
  summary: "脘腹胀满，肢体困倦，尿少色黄，大便溏泄不爽，纳少厌食，恶心呕吐；或面目肌肤发黄，色泽鲜明如橘子色，皮肤发痒;或身热起伏，汗出热不解。"
"Z0006":
  label: "寒湿困脾"
  summary: "脘腹胀或疼痛，泛恶欲吐，纳呆，口淡不渴，便溏，头身困重，面色晦黄，或面目肌肤发黄，色晦暗如烟熏或肢体浮肿，小便短少。"
"Z0007":
  label: "心血瘀阻"
  summary: "临床表现为心胸憋闷疼痛，痛引肩背，并可循手少阴心经向左上肢放射,口、唇、爪甲青紫,舌质暗红，或有瘀点、瘀斑等症状。轻者仅觉心胸疼痛，憋闷或隐痛不适，痛区固定，时发时休。剧者可突然发作，痛如刀割，悸惕不安，面色青白，唇暗肢冷，自汗，疼痛。"
"Z0008":
  label: "肺失宣泄，肺气不足"
  summary: "少气乏力，稍有劳作则气喘吁吁，呼吸气促；人体抗病能力低下，容易感染外邪，易于感冒，多有畏寒、流清涕之症；遇寒冷易发作鼻窦炎；常见皮肤干燥、皱缩、瘙痒，秋冬气候干燥时尤其突出；常可导致肾阳不足，使水液运行不利，出现尿频数，余沥不尽。"
"Z0011":
  label: "肝气郁结，肝血亏虚"
  summary: "情致方面容易出现情志抑郁，闷闷不乐，胸闷喜叹息。还可见胸肋胀痛或窜痛；女性还会出现乳房及小腹胀痛，以及引起月经不调、痛经等。气郁结在咽喉的部位，会出现喉咙有异物且咳又咳不出来的症状；气郁结在头部，会出现头痛、头晕等症状。肝气郁结合并肝血亏虚时常表现常表现为衰老迅速，心情失落，忧虑，焦躁不安、失眠多梦。"
"Z0012":
  label: "气血双虚"
  summary: "气血不足，体质虚弱，气虚则畏寒肢冷、自汗、头晕耳鸣、疲倦无力、心悸气短、发育迟缓。血虚可见面色无华萎黄、皮肤干燥、毛发枯萎、指甲干裂、视物昏花、手足麻木、失眠多梦、健忘心悸、精神恍惚。气血不足则神疲乏力、气短懒言、面色淡黄或萎黄、头晕目眩、唇甲色淡、心悸失眠。"
"Z0014":
  label: "肝火上炎"
  summary: "头晕胀痛，耳鸣，面红，目赤肿痛，急躁易怒，心烦不眠或多梦，口苦口干，便秘，尿短黄，或胁肋灼痛，衄血吐血，妇女月经量多、超前。肝火上炎上扰清窍则头晕胀痛；肝开窍于目，火性炎上则面红目赤肿痛；胆附于肝入耳，肝热移胆则耳鸣；肝火内扰，肝失条达，心神不宁则急躁易怒，心烦不眠或多梦；肝火郁于肝络则胁肋灼热疼痛；热盛伤津则日苦口干，便秘，尿短黄；肝火灼伤脉络，血热妄行则衄血吐血，经行量多，超前。"
"Z0015":
  label: "肝血亏虚"
  summary: "临床表现以筋脉、爪甲、两目、肌肤等失血濡养而见肢体麻木，关节拘急不利，手足震颤；爪甲干枯脆薄；视物模糊、眼花、视力减退，甚至雀盲，眩晕耳鸣；面、舌色淡等血虚症状。兼有虚烦多梦，易惊善恐，女性可有月经不调等症。"
"Z0016":
  label: "肝气郁结"
  summary: "情致方面容易出现情志抑郁，闷闷不乐，胸闷喜叹息。肝的气机调达能促进脾胃的消化，还可表现为脾胃消化功能下降，容易出现腹胀嗳气，食欲下降等。"
"Z0017":
  label: "胃阴虚"
  summary: "主要表现在胃脘隐痛，饥不欲食，口燥咽干，大便干结，或脘痞不舒，或干呕见逆。此证多由胃病久延不愈，或热病后期阴液未复，或平素嗜食辛辣，或情志不遂，气郁化火使胃阴耗伤而致。"
"Z0018":
  label: "胃气不足"
  summary: "胃脘隐痛或痞胀、按之觉舒，食欲不振，或得食痛缓，食后胀甚，嗳气，口淡不渴，面色萎黄，气短懒言，神疲倦怠等。"
"Z0019":
  label: "胆火旺"
  summary: "主要包括口干、口苦、眼睛有眼屎，有时候有耳鸣的症状、头晕目眩，还有口里有异味、不想吃东西、大便偏干、肝区隐隐不适，大便偶尔有里急后重的感觉，以及吃饭不香、胆囊区隐痛、头上长包，都可以是胆火旺的主要表现。测血压有时候血压会高，胖人可以头晕目眩、眼睛模糊，好多临床症状都属于肝胆火旺的表现。"
"Z0020":
  label: "胆气虚"
  summary: "不寐多梦，易于惊醒，胆怯恐惧，遇事易惊，心悸气短，倦怠，小便清长，或虚烦不寐，形体消瘦，面色晄白，易疲劳，或不寐心悸，虚烦不安，头目眩晕，口干咽燥。"
"Z0021":
  label: "脾气虚"
  summary: "不思饮食，食入不化，胃中嘈杂不适，隐痛；或干呕呃逆，口干咽燥，心烦消瘦，大便干结。"
"Z0010":
  label: "心火上炎"
  summary: "症见心胸烦热，口舌生疮，夜不成眠，舌尖红赤，兼见面红口渴。或见吐血衄血，小便短赤涩痛，大便秘结，甚或狂躁谵语。"
"Z0009":
  label: "心气不足"
  summary: "症见心悸、气短、自汗，胸闷不适，神疲体倦，面色淡白。"
"Z0013":
  label: "心血亏虚"
  summary: "症见心悸、气短、自汗，胸闷不适，神疲体倦，面色淡白。"
"Z0022":
  label: "恭喜您，脏腑功能良好"
  summary: ""
"Z0023":
  label: "脾阳虚"
  summary: ""
